version: "3.7"

services:

  cbrm:
    hostname: "cbrm"
    image: node:14.17.3
    environment:
      - NODE_TYPE=main-worker
    tty: true
    user: "1000:1000"
    volumes:
      - ".:/var/www"
    ports:
      - mode: host
        protocol: tcp
        published: 3000
        target: 3000
    command: [ "npm", "start" ]

  redis:
    image: redis:6
    ports:
      - mode: host
        protocol: tcp
        published: 6379
        target: 6379

  mailhog:
    image: mailhog/mailhog

