version: "3.7"

services:

  cbrm-test:
    hostname: "cbrm-test"
    image: node:16.14.0
    environment:
      - NODE_TYPE=main-worker
    tty: true
    user: "1000:1000"
    volumes:
      - ".:/var/www"
    ports:
      - "8000:3000"
    command: [ "npm", "run", "start-test" ]

  redis-test:
    image: redis:6

  mailhog-test:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

